import { useAuth } from './Auth';
import { useRef, useState, type ReactNode } from 'react';
import { ArrowRight, BookOpen, Bookmark, CheckCircle2, ChevronDown, ChevronLeft, ChevronRight, ClipboardList, Download, Flag, History, Play, RotateCcw, Search, Sparkles, Target, Upload, XCircle } from 'lucide-react';
import { getStatus, isCorrect, shuffled, validateBackup, type Question, type StudyState, type Session, type Progress } from './model';
import { QuestionCard } from './QuestionCard';
import { DomainResults } from './MockExam';
type Shared = {questions:Question[];state:StudyState};
export function PageHeading({eyebrow,title,description,action}:{eyebrow:string;title:string;description:string;action?:ReactNode}) {return <div className="page-heading"><div><div className="section-eyebrow">{eyebrow}</div><h1>{title}</h1><p>{description}</p></div>{action||<span className="pill">AWS SAA-C03</span>}</div>;}
export function Dashboard({questions,state,reviewCount,done,studied,correct,active,onStudy,onSetup,onResume,onReview,onStart}:Shared & {reviewCount:number;done:number;studied:number;correct:number;active?:Session;onStudy:()=>void;onSetup:()=>void;onResume:()=>void;onReview:()=>void;onStart:()=>void}) {
  const ratio=state.attempts.length?Math.round(correct/state.attempts.length*100):0;
  const days=Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-(6-i));return {date:d,count:state.attempts.filter(a=>new Date(a.at).toDateString()===d.toDateString()).length};});
  const max=Math.max(5,...days.map(d=>d.count));
  return <><PageHeading eyebrow="MY LEARNING SPACE" title="오늘도, 한 문제씩." description="쌓이는 이해만큼, 합격에 가까워집니다." action={<span className="date-label">{new Date().toLocaleDateString('ko-KR',{month:'long',day:'numeric',weekday:'long'})}</span>}/>
    <div className="stats-grid">
      <Stat label="직접 풀어본 문제" value={done} suffix={`/ ${questions.length}`} icon={<BookOpen size={19}/>} detail={`해설만 확인한 문제와 구분해요`}/>
      <Stat label="복습이 필요한 문제" value={reviewCount} suffix="문제" icon={<RotateCcw size={19}/>} detail="오답과 헷갈리는 문제" tone="amber"/>
      <Stat label="누적 정답률" value={state.attempts.length?ratio:'—'} suffix={state.attempts.length?'%':''} icon={<Target size={19}/>} detail={`총 ${state.attempts.length}회 풀이 기준`} tone="green"/>
      <Stat label="정답·해설 확인" value={studied} suffix="문제" icon={<CheckCircle2 size={19}/>} detail="공부 모드에서 살펴본 문제" tone="violet"/>
    </div>
    <div className="dashboard-grid"><section className="continue-card"><div className="continue-top"><span className="light-eyebrow">KEEP YOUR MOMENTUM</span><BookOpen size={23}/></div><h2>{active?'멈춘 곳에서, 다시 시작.':'오늘의 한 문제를 만나보세요.'}</h2><p>{active?`${active.mode==='mock'?'모의고사':active.mode==='review'?'오답 복습':'문제풀이'} 세트 · ${active.ids.length}문제 중 ${active.ids.filter(id=>active.answers[id]?.length).length}문제 응답`:`공부 모드 · ${String(state.studyIndex+1).padStart(3,'0')}번 문제부터 시작해요.`}</p><button className="button light" onClick={active?onResume:onStudy}>{active?'이어서 풀기':'공부 이어가기'}<ArrowRight size={17}/></button><div className="continue-footer"><span>나의 문제집 진도</span><b>{Math.round(done/questions.length*100)}%</b></div><div className="progress-track light-track"><span style={{width:`${done/questions.length*100}%`}}/></div></section>
      <section className="panel week-panel"><div className="panel-title"><div><div className="section-eyebrow">LITTLE BY LITTLE</div><h3>이번 주의 발자국</h3></div><span className="small-badge">최근 7일</span></div><div className="week-chart" aria-label="최근 7일 풀이 횟수">{days.map((d,i)=><div className={`day-column ${i===6?'today':''}`} key={i}><span className="bar-value">{d.count}</span><div className="bar-space"><div className="day-bar" style={{height:`${Math.max(3,d.count/max*100)}%`}}/></div><span className="day-name">{i===6?'오늘':d.date.toLocaleDateString('ko-KR',{weekday:'short'})}</span></div>)}</div><p className="microcopy">작은 반복이 단단한 이해를 만들어요.</p></section></div>
    <div className="section-heading"><h2>어떻게 공부할까요?</h2><span>오늘의 공부 방식을 골라보세요.</span></div><div className="mode-grid"><ModeCard icon={<BookOpen size={22}/>} label="개념을 이해하고 싶을 때" title="한 문제씩 공부하기" text="스스로 답을 떠올리고, 정답과 해설을 펼쳐보세요." action="공부하기" onClick={onStudy}/><ModeCard icon={<ClipboardList size={22}/>} label="실력을 확인하고 싶을 때" title={`새 문제 ${Math.min(20,questions.length)}개 풀기`} text="아직 풀지 않은 문제를 모아, 마지막에 한 번에 채점해요." action="바로 시작" onClick={onStart}/><ModeCard icon={<RotateCcw size={22}/>} label="확실하게 기억하고 싶을 때" title="오답 다시 만나기" text={reviewCount?`복습이 필요한 ${reviewCount}문제가 기다리고 있어요.`:'틀렸거나 헷갈린 문제를 이곳에 모아둘게요.'} action="오답노트 보기" onClick={onReview}/></div>
    <div className="home-bottom"><span><Sparkles size={16}/>원하는 분량과 범위로 나만의 세트를 만들 수도 있어요.</span><button className="text-button" onClick={onSetup}>세트 설정하기<ArrowRight size={15}/></button></div></>;
}
function Stat({label,value,suffix,icon,detail,tone='blue'}:{label:string;value:number|string;suffix:string;icon:ReactNode;detail:string;tone?:string}) {return <div className={`stat-card ${tone}`}><div className="stat-label">{label}<span className="stat-icon">{icon}</span></div><div className="stat-value">{value}<span>{suffix}</span></div><p>{detail}</p></div>;}
function ModeCard({icon,label,title,text,action,onClick}:{icon:ReactNode;label:string;title:string;text:string;action:string;onClick:()=>void}) {return <section className="mode-card"><div className="mode-icon">{icon}</div><small>{label}</small><h3>{title}</h3><p>{text}</p><button className="text-button" onClick={onClick}>{action}<ArrowRight size={16}/></button></section>;}
export function SessionSetup({questions,state,active,onStart,onResume}:Shared & {active?:Session;onStart:(ids:string[],mode:'quiz'|'review')=>void;onResume:()=>void}) {
  const [source,setSource]=useState('all'),[count,setCount]=useState(Math.min(20,questions.length)),[order,setOrder]=useState('random'),[from,setFrom]=useState(1),[to,setTo]=useState(questions.length);
  const pool=questions.filter(q=>{const s=getStatus(q.id,state);return q.number>=from&&q.number<=to&&(source==='all'||source==='new'&&!s.attempts.length||source==='review'&&s.needsReview||source==='bookmark'&&state.progress[q.id]?.bookmark);});
  const valid=Number.isInteger(count)&&count>=1&&count<=questions.length&&Number.isInteger(from)&&Number.isInteger(to)&&from>=1&&to<=questions.length&&from<=to;
  return <><PageHeading eyebrow="BUILD YOUR SESSION" title="오늘의 공부를 골라보세요." description="분량은 가볍게, 채점은 마지막에. 나에게 맞는 속도로 시작해요."/>{active&&<div className="resume-banner"><div><Play size={19}/><span>진행 중인 {active.ids.length}문제 세트가 있어요.</span></div><button className="text-button" onClick={onResume}>이어서 풀기<ArrowRight size={15}/></button></div>}<div className="setup-layout"><div className="panel setup-panel"><fieldset><legend><span>01</span>어떤 문제를 풀까요?</legend><div className="source-options">{[['all','전체 문제','처음부터 골고루'],['new','아직 안 푼 문제','새로운 문제 만나기'],['review','복습할 문제','오답과 헷갈림'],['bookmark','북마크한 문제','내가 저장한 문제']].map(([key,title,desc])=><label className={`source-option ${source===key?'selected':''}`} key={key}><input type="radio" name="pool" value={key} checked={source===key} onChange={()=>setSource(key)}/><strong>{title}</strong><span>{desc}</span></label>)}</div></fieldset><fieldset><legend><span>02</span>몇 문제를 풀까요?</legend><div className="count-options">{[...new Set([10,20,50,65].map(n=>Math.min(n,questions.length)))].map(n=><button key={n} className={count===n?'selected':''} onClick={()=>setCount(n)}>{n}문제</button>)}<label>직접 입력<input aria-label="풀이 문제 수" type="number" min={1} max={questions.length} value={count||''} onChange={e=>setCount(Number(e.target.value))}/></label></div></fieldset><fieldset><legend><span>03</span>범위와 순서를 정해주세요.</legend><div className="range-row"><label>시작 번호<input aria-label="시작 번호" type="number" min={1} max={questions.length} value={from||''} onChange={e=>setFrom(Number(e.target.value))}/></label><span>–</span><label>마지막 번호<input aria-label="마지막 번호" type="number" min={1} max={questions.length} value={to||''} onChange={e=>setTo(Number(e.target.value))}/></label><label>출제 순서<select value={order} onChange={e=>setOrder(e.target.value)}><option value="random">무작위로</option><option value="sequential">번호순으로</option></select></label></div></fieldset></div><aside className="panel setup-summary"><div className="section-eyebrow">READY WHEN YOU ARE</div><h3>나의 학습 세트</h3><div className="session-number">{valid?Math.min(count,pool.length):0}<span>문제</span></div><div className="summary-line"><span>조건에 맞는 문제</span><strong>{pool.length}개</strong></div><div className="summary-line"><span>정답 공개</span><strong>전체 제출 후</strong></div><div className="summary-line"><span>이어풀기</span><strong>자동 저장</strong></div><button className="button primary full-width" disabled={!valid||!pool.length} onClick={()=>onStart((order==='random'?shuffled(pool):pool).slice(0,count).map(q=>q.id),source==='review'?'review':'quiz')}>문제풀이 시작<ArrowRight size={17}/></button><p className="microcopy">{!valid?'문제 수와 번호 범위를 확인해 주세요.':!pool.length?'선택한 조건에 해당하는 문제가 없습니다.':pool.length<count?'해당하는 문제를 모두 모아 시작합니다.':'답을 보지 않고 스스로 풀어보세요.'}</p></aside></div></>;
}
export function Collection({kind,questions,state,onStudy,onStart,onProgress}:Shared & {kind:'review'|'bookmarks';onStudy:(index:number)=>void;onStart:(ids:string[])=>void;onProgress:(id:string,p:Partial<Progress>)=>void}) {
  const [filter,setFilter]=useState('active'),[query,setQuery]=useState(''),[page,setPage]=useState(0);
  const all=questions.filter(q=>{const s=getStatus(q.id,state);return kind==='bookmarks'?state.progress[q.id]?.bookmark:filter==='active'?s.needsReview:filter==='ever'?s.everWrong:filter==='mastered'?s.everWrong&&!s.needsReview:!!state.progress[q.id]?.unsure;});
  const filtered=all.filter(q=>!query||`${q.number} ${q.prompt} ${q.choices.map(c=>c.text).join(' ')}`.toLowerCase().includes(query.toLowerCase()));
  const shown=filtered.slice(page*20,(page+1)*20);
  return <><PageHeading eyebrow={kind==='review'?'MAKE IT STICK':'SAVED FOR LATER'} title={kind==='review'?'다시 만나면, 더 단단하게.':'기억해 두고 싶은 문제들.'} description={kind==='review'?'틀린 문제와 헷갈린 문제를 모았어요. 두 번 연속 맞히면 익숙해짐으로 이동해요.':'중요한 문제를 저장해 두고, 필요할 때 다시 꺼내보세요.'}/><div className="collection-toolbar"><div className="segmented">{kind==='review'?[['active','복습 필요'],['ever','과거 오답 전체'],['unsure','헷갈림'],['mastered','익숙해짐']].map(([key,label])=><button className={filter===key?'active':''} key={key} onClick={()=>{setFilter(key);setPage(0);}}>{label}</button>):<span className="collection-count">저장한 문제 <b>{all.length}</b></span>}</div><button className="button primary" disabled={!filtered.length} onClick={()=>onStart(shuffled(filtered).map(q=>q.id))}><RotateCcw size={16}/>선택 목록 다시 풀기</button></div><div className="search-row"><label className="search-input"><Search size={17}/><input aria-label="문제 검색" placeholder="문제 번호 또는 키워드로 검색" value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}}/></label><span>{filtered.length}문제</span></div>
    {!filtered.length?<Empty icon={kind==='review'?<CheckCircle2 size={34}/>:<Bookmark size={34}/>} title={query?'검색 결과가 없어요.':kind==='review'?'이 목록에 해당하는 문제가 없어요.':'아직 저장한 문제가 없어요.'} text={kind==='review'?'문제를 풀거나 ‘헷갈려요’를 표시하면 복습할 문제가 모입니다.':'문제 오른쪽 위의 북마크 버튼을 눌러 저장해 보세요.'}/>:<div className="question-list">{shown.map(q=>{const s=getStatus(q.id,state);return <article className="list-row" key={q.id}><span className="list-number">{String(q.number).padStart(3,'0')}</span><div className="list-content"><button className="list-prompt" onClick={()=>onStudy(q.number-1)}>{excerpt(q.prompt)}</button><div className="list-meta"><span>풀이 {s.attempts.length}회</span><span className="red-text">오답 {s.attempts.filter(a=>!a.correct).length}회</span>{s.everWrong&&!s.needsReview&&<span className="green-text">익숙해짐</span>}{state.progress[q.id]?.unsure&&<span className="amber-text">헷갈림</span>}{s.latest&&<span>최근 {s.latest.correct?'정답':'오답'}</span>}</div></div><button className={`icon-button ${state.progress[q.id]?.bookmark?'bookmarked':''}`} aria-label={`${q.number}번 북마크 ${state.progress[q.id]?.bookmark?'해제':'추가'}`} onClick={()=>onProgress(q.id,{bookmark:!state.progress[q.id]?.bookmark})}><Bookmark size={17} fill={state.progress[q.id]?.bookmark?'currentColor':'none'}/></button><button className="icon-button" aria-label={`${q.number}번 공부하기`} onClick={()=>onStudy(q.number-1)}><ChevronRight size={18}/></button></article>;})}</div>}
    <Pagination page={page} total={filtered.length} size={20} onChange={setPage}/>{kind==='review'&&<p className="collection-footnote">‘헷갈림’ 표시는 직접 해제할 때까지 유지됩니다. 익숙해진 문제도 과거 오답 전체에서 다시 볼 수 있어요.</p>}</>;
}
export function Results({session,questions,state,onProgress,onRetry,onHome}:Shared & {session?:Session;onProgress:(id:string,p:Partial<Progress>)=>void;onRetry:(ids:string[])=>void;onHome:()=>void}) {
  const [filter,setFilter]=useState('all'),[page,setPage]=useState(0);
  if(!session?.submittedAt)return <Empty icon={<History size={32}/>} title="아직 제출한 결과가 없어요." text="세트를 제출하면 이곳에서 정답과 해설을 확인할 수 있어요."/>;
  const items=session.ids.map(id=>{const q=questions.find(x=>x.id===id)!;const chosen=session.answers[id]||[];return {q,chosen,status:!chosen.length?'skip':isCorrect(chosen,q.answer)?'correct':'wrong'};});
  const right=items.filter(i=>i.status==='correct'),wrong=items.filter(i=>i.status==='wrong'),skip=items.filter(i=>i.status==='skip');
  const visible=items.filter(i=>filter==='all'||filter===i.status||filter==='unsure'&&state.progress[i.q.id]?.unsure);
  const retry=items.filter(i=>i.status!=='correct'||state.progress[i.q.id]?.unsure);
  return <><PageHeading eyebrow="SESSION COMPLETE" title="오늘의 공부가 쌓였어요." description={`${formatDate(session.submittedAt)} · ${session.mode==='mock'?'모의고사':session.mode==='review'?'오답 복습':'문제풀이'} ${items.length}문제`}/><section className="result-summary"><div className="score-circle" style={{'--score':`${right.length/items.length*100}%`} as React.CSSProperties}><div><strong>{Math.round(right.length/items.length*100)}<small>%</small></strong><span>이번 세트 정답률</span></div></div><div className="result-counts"><div><CheckCircle2 size={18}/><strong>{right.length}</strong><span>정답</span></div><div><XCircle size={18}/><strong>{wrong.length}</strong><span>오답</span></div><div><ChevronRight size={18}/><strong>{skip.length}</strong><span>건너뜀</span></div></div><div className="result-actions"><button className="button primary" disabled={!retry.length} onClick={()=>onRetry(retry.map(i=>i.q.id))}><RotateCcw size={16}/>오답·건너뜀·헷갈림 다시 풀기</button><button className="button secondary" onClick={onHome}>학습 홈으로</button><p className="microcopy">오답 {wrong.length}문제가 복습 기록에 반영되었습니다.</p></div></section><DomainResults session={session} questions={questions}/><div className="collection-toolbar"><div className="segmented">{[['all','전체'],['wrong','오답'],['skip','건너뜀'],['unsure','헷갈림']].map(([key,label])=><button key={key} className={filter===key?'active':''} onClick={()=>{setFilter(key);setPage(0);}}>{label}</button>)}</div><span className="muted">{visible.length}문제</span></div>{!visible.length?<Empty icon={<CheckCircle2 size={30}/>} title="해당하는 문제가 없어요." text="다른 필터에서 풀이 결과를 확인해 보세요."/>:<div className="results-list">{visible.slice(page*10,(page+1)*10).map(({q,chosen,status})=><details key={q.id} className="result-detail"><summary><span className={`result-status ${status}`}>{status==='correct'?'정답':status==='wrong'?'오답':'건너뜀'}</span><span className="list-number">{String(q.number).padStart(3,'0')}</span><span className="result-prompt">{excerpt(q.prompt)}</span><ChevronDown size={17}/></summary><QuestionCard question={q} selected={chosen} revealed={true} onSelect={()=>{}} progress={state.progress[q.id]||{}} onProgress={p=>onProgress(q.id,p)} fontSize={state.fontSize} resultOnly/></details>)}</div>}<Pagination page={page} total={visible.length} size={10} onChange={setPage}/></>;
}
export function HistoryView({state,questions,onResults,onResume,onStudy}:Shared & {onResults:(id:string)=>void;onResume:(id:string)=>void;onStudy:(index:number)=>void}) {
  const [tab,setTab]=useState('sessions'),[page,setPage]=useState(0);
  const sessions=[...state.sessions].reverse(),attempts=[...state.attempts].reverse();
  return <><PageHeading eyebrow="YOUR LEARNING JOURNEY" title="차곡차곡 쌓인 공부의 기록." description="이전 세트의 결과를 확인하고, 멈춘 세트는 이어서 풀 수 있어요."/><div className="collection-toolbar"><div className="segmented"><button className={tab==='sessions'?'active':''} onClick={()=>{setTab('sessions');setPage(0);}}>세트 기록 {sessions.length}</button><button className={tab==='attempts'?'active':''} onClick={()=>{setTab('attempts');setPage(0);}}>전체 풀이 {attempts.length}</button></div></div>{tab==='sessions'?sessions.length?<div className="history-list">{sessions.slice(page*15,(page+1)*15).map(s=>{const correct=s.ids.filter(id=>isCorrect(s.answers[id]||[],questions.find(q=>q.id===id)!.answer)).length;return <article key={s.id} className="history-row"><div className="history-icon">{s.mode==='review'?<RotateCcw size={21}/>:<ClipboardList size={21}/>}</div><div className="history-info"><h3>{s.mode==='mock'?'모의고사':s.mode==='review'?'오답 복습':'문제풀이'} · {s.ids.length}문제</h3><p>{formatDate(s.startedAt)}</p></div><span className={`history-score ${!s.submittedAt?'muted':''}`}>{s.submittedAt?`${correct} / ${s.ids.length}`:'진행 중'}</span><button className="button secondary" onClick={()=>s.submittedAt?onResults(s.id):onResume(s.id)}>{s.submittedAt?'결과 보기':'이어서 풀기'}<ChevronRight size={15}/></button></article>;})}</div>:<Empty icon={<History size={34}/>} title="첫 번째 세트를 기다리고 있어요." text="문제풀이를 시작하면 진행 상황과 결과가 여기에 남아요."/>:attempts.length?<div className="question-list">{attempts.slice(page*15,(page+1)*15).map(a=>{const q=questions.find(q=>q.id===a.qid)!;return <article key={a.id} className="list-row"><span className={`result-status ${a.correct?'correct':'wrong'}`}>{a.correct?'정답':'오답'}</span><div className="list-content"><button className="list-prompt" onClick={()=>onStudy(q.number-1)}>Q{q.number} · {excerpt(q.prompt)}</button><div className="list-meta"><span>{formatDate(a.at)}</span><span>{a.mode==='study'?'공부 모드':a.mode==='mock'?'모의고사':a.mode==='review'?'오답 복습':'문제풀이'}</span><span>내 선택 {a.selected.join(', ')}</span></div></div></article>;})}</div>:<Empty icon={<BookOpen size={34}/>} title="아직 풀이 기록이 없어요." text="답을 선택하고 채점한 기록이 쌓입니다. 해설만 읽은 문제는 점수에 포함되지 않아요."/>}<Pagination page={page} total={tab==='sessions'?sessions.length:attempts.length} size={15} onChange={setPage}/></>;
}
export function SettingsView({state,questions,onFont,onImport,onNotice}:Shared & {onFont:(size:number)=>void;onImport:(s:StudyState)=>void;onNotice:(text:string)=>void}) {
  const file=useRef<HTMLInputElement>(null);
  const {user}=useAuth();
  function download() {const blob=new Blob([JSON.stringify({app:'saa-study',exportedAt:new Date().toISOString(),state},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`SAA-학습기록-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);onNotice('학습 기록 백업 파일을 내려받았습니다.');}
  return <><PageHeading eyebrow="YOUR PERSONAL SPACE" title="공부하기 편한 환경으로." description="글자 크기를 조절하고, 소중한 공부 기록을 백업하세요."/><div className="settings-grid"><section className="panel"><div className="section-eyebrow">READING COMFORT</div><h2>글자 크기</h2><p className="muted">문제와 보기의 글자 크기에 적용됩니다.</p><label className="font-setting">크기<select aria-label="기본 글자 크기" value={state.fontSize} onChange={e=>onFont(Number(e.target.value))}>{[16,17,18,19,20,21,22].map(n=><option key={n} value={n}>{n}px{n===17?' · 기본':''}</option>)}</select></label><div className="font-preview" style={{fontSize:state.fontSize}}>매일 한 문제씩, 나의 속도로 공부해요.</div></section><section className="panel"><div className="section-eyebrow">KEEP YOUR PROGRESS SAFE</div><h2>학습 기록 백업</h2><p className="muted">풀이 이력, 오답, 북마크, 메모, 진행 중인 세트를 한 파일에 저장합니다.</p><div className="backup-actions"><button className="button primary" onClick={download}><Download size={17}/>백업 내려받기</button><button className="button secondary" onClick={()=>file.current?.click()}><Upload size={17}/>백업 불러오기</button></div><input ref={file} type="file" accept=".json,application/json" aria-label="백업 파일 선택" className="sr-only" onChange={async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;try{if(f.size>50*1024*1024)throw Error('50MB 이하의 백업 파일을 선택해 주세요.');const parsed=JSON.parse(await f.text());onImport(validateBackup(parsed,questions,state.bankId));}catch(err){onNotice(err instanceof Error?err.message:'백업 파일을 읽지 못했습니다.');}}}/><div className="storage-note"><strong>{user?'기록은 내 계정에 자동 저장돼요.':'기록은 이 브라우저에 저장돼요.'}</strong><p>{user?'다른 기기에서는 같은 계정으로 로그인하세요. JSON 백업은 별도 보관이 필요할 때만 사용하면 됩니다.':'다른 브라우저나 PC에서는 백업 파일을 불러오면 이어서 공부할 수 있습니다. 브라우저 데이터를 지우기 전에는 백업을 내려받아 주세요.'}</p></div></section><section className="panel source-info"><div className="section-eyebrow">ABOUT YOUR QUESTION BANK</div><h2>내 문제집</h2><dl><div><dt>문제집</dt><dd>AWS SAA-C03 · 한국어</dd></div><div><dt>문제 수</dt><dd>{questions.length}문제 · 복수 정답 {questions.filter(q=>q.answer.length>1).length}문제</dd></div><div><dt>원본</dt><dd>{Math.max(...questions.map(q=>q.pageEnd)) || '데모'}{questions.some(q=>q.pageEnd>0)?'페이지':' 문제집'}</dd></div><div><dt>채점 기준</dt><dd>현재 문제집에 기재된 정답</dd></div></dl><p className="muted">원문의 정답과 해설을 그대로 사용합니다. 내용이 의심될 때에는 원문과 참고 자료를 확인하고 메모를 남겨두세요. 중복된 원문 번호는 문서 순서에 따른 학습 번호로 구분했습니다.</p></section></div></>;
}
function Empty({icon,title,text}:{icon:ReactNode;title:string;text:string}){return <div className="empty-state">{icon}<h2>{title}</h2><p>{text}</p></div>;}
function Pagination({page,total,size,onChange}:{page:number;total:number;size:number;onChange:(page:number)=>void}) {if(total<=size)return null;return <div className="pagination"><button className="icon-button" aria-label="이전 페이지" disabled={page===0} onClick={()=>onChange(page-1)}><ChevronLeft size={16}/></button><span>{page+1} / {Math.ceil(total/size)}</span><button className="icon-button" aria-label="다음 페이지" disabled={(page+1)*size>=total} onClick={()=>onChange(page+1)}><ChevronRight size={16}/></button></div>;}
function excerpt(text:string){const cleaned=text.replace(/\[\[image:[^\]]+\]\]/g,'[도표]');return cleaned.length>125?cleaned.slice(0,125)+'…':cleaned;}
function formatDate(text:string){return new Date(text).toLocaleString('ko-KR',{month:'long',day:'numeric',hour:'2-digit',minute:'2-digit'});}
